import type { Metadata } from "next";
import { inter, judson, cormorant_garamond } from "@/lib/fonts";
import "./globals.scss";
import Header from "@/components/static/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={judson.variable + " " + cormorant_garamond.variable}>
        <Header />
        {children}
      </body>
    </html>
  );
}
